### ISSUE TITLE
When I approve a verification (claim) the reward of 100 BOR is not shown in my account

### ISSUE THREAD

**Issue by natillasol** [cambiatus/frontend#57] opened 2019-11-14 14:19 UTC
**Describe the bug**
When I approve a verification (claim) the reward of 100 BOR is not shown in my account. 

**To Reproduce**
1. Go to 'borboins.cambiatus.io
2. Click on 'Activities for your analysis'
3. Click on "Approve"
4. Go back to Dashboard

**Expected behavior**
When you check the account (balance) you won't have the 100 BORs that you were meant to earn

**Screenshots**

**Cambiatus Env you are using**
borboins.cambiatus.io

**Comment by lucca65** [comment] 2019-11-14 18:24
closing this as this is a duplicate of #58

**Closed by lucca65** 2019-11-14 18:24 UTC
Labels: bug
