### ISSUE TITLE
Changes on Profile and Public profile

### ISSUE THREAD

**Issue by heltonlr** [cambiatus/frontend#298] opened 2020-07-16 11:35 UTC
**Defined changes:**

- Show location and map on company profile;
- Remove the "download the 12 words" for both profiles
- Show the new information that was added during registration (https://www.figma.com/file/47BEsGEMSWfhTm3zC0ugyA/Main-flow?node-id=3%3A2206)

**More details, here:**
https://www.figma.com/file/47BEsGEMSWfhTm3zC0ugyA/Main-flow?node-id=948%3A468

**Comment by lucca65** [comment] 2020-07-17 18:42
This will require us to finish reworking the registration if the community has enabled KYC.

Also we will not remove the download PDF anymore

**Comment by heltonlr** [comment] 2020-07-17 18:58
> This will require us to finish reworking the registration if the community has enabled KYC.
> 
> Also we will not remove the download PDF anymore

Ok

**Comment by heltonlr** [comment] 2020-07-17 18:58
Ok

**Comment by lucca65** [comment] 2020-10-21 10:52
duplicate of #361

**Closed** 2020-10-21 10:52 UTC
Labels: duplicate
