### ISSUE TITLE
"Reinvidicar" button is not available for the new actions

### ISSUE THREAD

**Issue by flaviagoma** [cambiatus/frontend#115] opened 2019-12-19 00:55 UTC
**Describe the bug**
At the community section, under the item "Incentivar hábitos que mudam o mundo" the buttons that allow us to claim the coins for those offers is not displayed. Therefore the action cannot be claimed. 

**To Reproduce**
1. Go to dashboard 
2. Click on explore
3. Scroll down and click to on "Incentivar hábitos que mudam o mundo"

**Expected behavior**
Each action should display a 'reivindicar' button.

**Screenshots**

![Screenshot_20191218-212958](https://user-images.githubusercontent.com/58967850/71135196-c719c580-21df-11ea-9fe7-3cbf75a79449.jpg)

**Cambiatus Env you are using**

https://muda.cambiatus.io/community/MUDA

**Smartphone (please complete the following information):**
 - Device: ASUS_X00HD
 - OS: Android 8.1.0
 - Browser Chrome 
 - Version: 79.0.3945.79

**Additional context**

**Comment by zacck** [comment] 2019-12-19 05:22
@flaviagoma  this is because this action is automatic, i.e does not allow one to claim, however it still needs to have someone do the awarding, which @lucca65  and I are still figuring out how to provide a UI for

**Comment by lucca65** [comment] 2019-12-19 05:30
@zacck actually, automatic is an action that is done by a bot or similar software. so there will probably not have an UI to do this.

@heltonr maybe the interface can have a different section or way to show automatic actions? 

I’ll close this issue for now as this is the expected behavior. 

please feel free to continue the discussion, if we have a use case where this is necessary we can reopen it!

**Closed** 2019-12-19 05:30 UTC
Labels: question

**Comment by flaviagoma** [comment] 2019-12-19 07:37
Ok, so summing up you guys are still figuring out how the person will get rewarded for an action that needs no external validation, right? 
So, at this initial phase our idea was to build these actions based on trust, the user will have total control over it. So I imagine that we will need a button somewhere so they can say they did the action and then get the reward, correct?

**Comment by zacck** [comment] 2019-12-19 07:46
@flaviagoma I was wrong, there is a system that awards automatic actions it's just not a human system. 

If you are building trust based actions, then for all intents and purposes we can say that the system will take care of doing those rewards. In other words there won't be a button  the `system` will do the rewarding. I hope this clears things up

**Comment by flaviagoma** [comment] 2019-12-19 08:18
Sorry @zacck but now I am even more intrigued 😬😅. There will be no button at all? How will the system know if the user wants to claim that action if there is not a button? How will it know who to reward? 🤔    It's probably a silly question. Anyway, I will let you guys do your thing and I can catch up if the implementation once it's settled.

**Comment by lucca65** [comment] 2019-12-19 15:33
@flaviagoma actually this type of questions are perfect. This is because with this information you folks at MUDA will be able to know what you can do with the system. We have some level of documentation for our code, but not for our platform yet. Those discussions can be referenced in the future until we build a guide or something.

I'll give you an example from Fundes, which is the most mature community that is using our platform.

They have actions that reward users for watching videos and answering a few questions afterwards. Fundes developed an app that shows those videos and questions to the users. Once the app knows for sure that the user completed the thing, their app invoke an automatic action. So in this flow there is no need for the user to get in the app, open a claim and another human to verify that the user really did watched the videos and answered the questions.

This is an example where a system checks and validates an action without any human check or interaction with the platform. These types of actions may appear on MUDA as you folks start building your own interface. 

Image for example that when someone buys a ticket for a MUDA event or share a tweet during an event they should receive a reward. You folks can build an app that checks that and automatically rewards users.

As you can imagine this is more "advanced" as it requires a bot or a system that runs besides Cambiatus.

**Comment by flaviagoma** [comment] 2019-12-19 17:20
Hi @lucca65 great to know! So in this case I belive our actions should not be automatic, because there is no system input from the user to trigger the reward. Maybe we should move back to manual validation or are there other possibilities?

**Comment by lucca65** [comment] 2019-12-19 17:22
Yeah I think so as well. If you require human interaction during the validation of an action, manual is the way to go!

**Comment by flaviagoma** [comment] 2019-12-19 17:35
@lucca65 actually we were trying to avoid this human validation. Is there a way to have the normal claim button and the system automatically approves it??g

**Comment by lucca65** [comment] 2019-12-19 17:38
Yeah, you’ll have to develop a software that validate those stuff, we can provide assistance and examples to the developer if needed
