### ISSUE TITLE
Verification access

### ISSUE THREAD

**Issue by natillasol** [cambiatus/frontend#51] opened 2019-11-13 19:09 UTC
**Is your feature request related to a problem? Please describe.**

When you click in any of the last actions (see red circle in screenshot) it takes you to a page that says:  "verification.title .   Cannot return null for non-nullable field"

This happens because I have not been assigned the role of verifier. 

**Describe the solution you'd like**
So I think that instead of : "verification.title .  Cannot return null for non-nullable field" it should say something more along the lines of : "You have not been assigned as a verifier"

**Describe alternatives you've considered**

**Additional context**
<img width="1440" alt="Screen Shot 2019-11-13 at 13 04 11" src="https://user-images.githubusercontent.com/57719975/68795514-c0af9100-0616-11ea-89d4-cee40fa45072.png">
<img width="1440" alt="Screen Shot 2019-11-13 at 13 04 06" src="https://user-images.githubusercontent.com/57719975/68795515-c0af9100-0616-11ea-9180-05e05a256af1.png">

**Comment by lucca65** [comment] 2019-11-14 00:06
hey this is a duplicate of #40 

I'll close this and we can track it there

**Closed by lucca65** 2019-11-14 00:06 UTC
