### ISSUE TITLE
User needs type "/dashboard" at URL to enter on the app

### ISSUE THREAD

**Issue by heltonlr** [cambiatus/frontend#95] opened 2019-12-05 14:13 UTC
**Describe the bug**
User needs write **"/dashboard"** at URL to enter (example: **muda.cambiatus.io/dashabord**).

**To Reproduce**
1. Open browser and type **muda.cambiatus.io**

**Expected behavior**
Should work even not typing /dashboard

**Screenshots**
--

**Cambiatus Env you are using**
Put the URL of the page you are trying to use

**Desktop (please complete the following information):**
 - OS: all
 - Browser: all
 - Version all

**Smartphone (please complete the following information):**
 - Device: all
 - OS: all
 - Browser: all
 - Version: all

**Additional context**
- Occurs only when user accesses a second time;
- Muda is only an example, should to work for all;

**Comment by lucca65** [comment] 2019-12-10 14:22
duplicate of #45

**Closed by lucca65** 2019-12-10 14:22 UTC
Labels: bug
