### ISSUE TITLE
Error while trying to export the private key

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#211] opened 2020-03-31 01:23 UTC
**Describe the bug**
App don't respond when trying to export the private key/PDF from the profile.

In development mode we get an JS error, displayed in the print screen below

**To Reproduce**
1. Go to 'Profile'
2. Click on the key icon
3. See error

**Expected behavior**
A PDF download of the private key

**Screenshots**
<img width="1057" alt="Screen Shot 2020-03-30 at 22 20 37" src="https://user-images.githubusercontent.com/1082127/77976937-b1369900-72d4-11ea-8fcc-6acf3092178b.png">

**Cambiatus Env you are using**
app.cambiatus.io

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
Discovered by @zequez

**Comment by amiskov** [comment] 2020-04-03 07:02
As far as I can see, the problem is that there are 2 buttons in [Page/Profile.elm#L215](https://github.com/cambiatus/frontend/blob/master/src/elm/Page/Profile.elm#L215), one above the other. In browser it renders like there's only 1 button. Here I shifted one of them in browser tools to demonstrate:

![image](https://user-images.githubusercontent.com/140053/78333068-d60b6480-7591-11ea-9521-f7ac9e4c815c.png)

The button above (which we actually click) tries to download PDF and fails, because PDF generator tries to find the text in HTML elements, which presented only on "Congratulations" page (page appears after the registration of the user).

The button below works fine, but it only shows the private key without generating PDF.

It's unclear, what is the right way to handle click on this button. Should we download PDF or just show the private key?

**Comment by lucca65** [comment] 2020-04-03 14:45
nice investigation @amiskov. Yeah, profile screen is one that we still have to rework. We started a redesign that is still ongoing for some less used screens. Profile page is one of them. The correct behaviour would be to download the PDF.

I think the right way to do it is, instead of copying from the existing elements, we'll need to change that port to take the private key from the local storage, and generate the PDF from it. Then it will work on both scenarios.

**Comment by amiskov** [comment] 2020-04-13 12:42
I started working on this issue. Need to do some exploration at first and then I'll create a WIP PR and likely ask some questions.

**Comment by amiskov** [comment] 2020-04-13 14:59
I think I need Profile page design mock-ups to handle this issue properly. @lucca65, can you please provide me these mock-ups in Figma?

**Comment by amiskov** [comment] 2020-04-13 15:09
> I think the right way to do it is, instead of copying from the existing elements, we'll need to change that port to take the private key from the local storage, and generate the PDF from it. Then it will work on both scenarios.

If I understand everything right, the PDF generated from the Profile should be different then PDF, displayed to the user after the registration:

- PDF from the Profile page can't contain 12-words passphrase (we display it to the user only once, during the registration process).
- Phrase "This is the only chance you have to download it!" is inappropriate for PDF, downloaded from the profile. User can download this PDF anytime.

To provide a proper solution for this cases, I think I should check Figma designs for the Profile first.

**Comment by lucca65** [comment] 2020-04-14 17:47
@amiskov sorry it took me while to reply. Here are the designs for the new profile page:

https://www.figma.com/file/47BEsGEMSWfhTm3zC0ugyA/Main-flow?node-id=21%3A53

The PDF should be the same as the one we got during the login, I'll ping you for a call so we can sort this out

**Comment by amiskov** [comment] 2020-06-30 16:10
This issue will be fixed in #270 while redisigning the Profile Page.

**Closed** 2020-07-21 12:46 UTC
Labels: bug, duplicate, help wanted
